const $=id=>document.getElementById(id);let page,info;
const labels={choosing:'選擇儲存位置',downloading:'下載中',merging:'合併影音',verifying:'驗證完整影音',completed:'已儲存 · 驗證通過',cancelled:'已取消',failed:'下載失敗'};
function message(text,error=false){$('message').textContent=text;$('message').hidden=!text;$('message').classList.toggle('error',error);}
async function send(action,data={}){const reply=await chrome.runtime.sendMessage({action,...data});if(!reply?.ok)throw new Error(reply?.error||'擴充連線失敗。');return reply.data;}
async function run(button,fn){button.disabled=true;try{await fn();}catch(e){message(e.message,true);}finally{button.disabled=false;}}
function context(){return {url:page.url,tabId:page.tabId};}
$('help').onclick=()=>chrome.runtime.openOptionsPage();
$('probe').onclick=()=>readQuality(false);
function readQuality(reuse){return run($('probe'),async()=>{message('正在啟動助手、讀取畫質…');info=await send('probe',{...context(),reuse});$('title').textContent=info.title;$('detail').textContent=`${info.uploader||'YouTube'} · ${Math.floor(info.duration/60)} 分 ${Math.floor(info.duration%60)} 秒`;$('quality').replaceChildren();for(const q of info.qualities){const shorter=Math.min(q.width||q.height,q.height);$('quality').add(new Option(`${shorter}p${shorter>=2160?' · 4K':''}${q.width<q.height?` · ${q.width} × ${q.height}`:''}`,String(q.height)));}$('quality').value=String((info.qualities.find(q=>Math.min(q.width||q.height,q.height)<=1080)||info.qualities[0]).height);$('settings').hidden=false;$('probe').textContent='重新讀取畫質';message('選畫質後下載。檔案完整驗證通過才會保存。');});}
$('download').onclick=()=>run($('download'),async()=>{message('請在另存新檔視窗選擇位置。');const result=await send('start',{...context(),quality:$('quality').value});message(result.cancelled?'已取消。':'下載已開始，關閉面板仍會繼續。');document.querySelector('details').open=true;});
function button(text,action){const b=document.createElement('button');b.className='text';b.textContent=text;b.onclick=()=>run(b,action);return b;}
function render(history){$('history').replaceChildren();$('count').textContent=history.length?String(history.length):'';const active=history.some(j=>!['completed','cancelled','failed'].includes(j.status));$('state').textContent=active?'工作中 · 關閉面板仍會繼續':'按下才啟動 · 完成後退出';for(const j of history){const item=document.createElement('article'),title=document.createElement('p'),state=document.createElement('p');title.className='job-title';title.textContent=j.title;state.className='muted'+(j.status==='failed'?' error':'');state.textContent=(labels[j.status]||j.status)+(j.progress>0&&j.progress<100?` · ${Math.round(j.progress)}%`:'')+(j.error?` · ${j.error}`:'');item.append(title,state);if(!['completed','cancelled','failed'].includes(j.status)){const p=document.createElement('progress');p.max=100;if(j.progress)p.value=j.progress;item.append(p);if(j.status!=='choosing')item.append(button('取消',()=>send('cancel',{id:j.id})));}if(j.status==='completed')item.append(button('在資料夾中顯示',()=>send('reveal',{id:j.id})));$('history').append(item);}}
$('clear').onclick=()=>run($('clear'),()=>send('clear'));
chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.history)render(changes.history.newValue||[]);});
chrome.storage.local.get('history').then(({history=[]})=>render(history));
send('page').then(result=>{page=result;$('title').textContent=page.url?page.title:'開啟 YouTube 影片';$('probe').disabled=!page.url;if(!page.url)$('detail').textContent='支援 YouTube 一般影片及 Shorts。';else readQuality(true);}).catch(e=>message(e.message,true));
