import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {webcrypto} from 'node:crypto';import {videoId,videoUrl} from '../extension/youtube.js';
test('only exact HTTPS YouTube video identities are accepted',()=>{for(const url of ['https://www.youtube.com/watch?v=yRRQ6filg-E&list=123','https://youtu.be/yRRQ6filg-E','https://www.youtube.com/shorts/yRRQ6filg-E'])assert.equal(videoUrl(url),'https://www.youtube.com/watch?v=yRRQ6filg-E');for(const url of ['http://www.youtube.com/watch?v=yRRQ6filg-E','https://youtube.com.evil.com/watch?v=yRRQ6filg-E','https://user@www.youtube.com/watch?v=yRRQ6filg-E','https://www.youtube.com:444/watch?v=yRRQ6filg-E','https://www.youtube.com/shorts/bad'])assert.equal(videoId(url),null);});
function background(){const state={history:[]},events={},root='chrome-extension://test/',calls=[];let tab={id:1,url:'https://www.youtube.com/watch?v=yRRQ6filg-E',title:'News - YouTube',windowId:3},native;
const event=name=>({addListener(fn){events[name]=fn;}});const chrome={runtime:{id:'test',getURL:p=>root+p,onMessage:event('message'),connectNative(){calls.push('connect');native={onMessage:event('nativeMessage'),onDisconnect:event('nativeDisconnect'),postMessage(m){calls.push(m.action);queueMicrotask(()=>events.nativeMessage({id:m.id,ok:true,data:m.action==='probe'?{id:'yRRQ6filg-E',title:'News',duration:103,qualities:[{height:1080,width:1920}]}:{id:m.jobId}}));},disconnect(){calls.push('disconnect');events.nativeDisconnect();}};return native;}},storage:{local:{get:async()=>structuredClone(state),set:async v=>Object.assign(state,structuredClone(v))}},tabs:{query:async()=>[tab]},action:{openPopup:async()=>{calls.push('popup');}}};
vm.runInNewContext(fs.readFileSync(new URL('../extension/background.js',import.meta.url),'utf8').replace(/^import .*;\r?\n/,''),{chrome,videoId,videoUrl,URL,crypto:webcrypto,setTimeout,clearTimeout,console,Date});
const send=(m,s={id:'test',url:root+'popup.html'})=>new Promise(resolve=>events.message(m,s,resolve));return {calls,state,send,events,tab:t=>tab=t};}
const url='https://www.youtube.com/watch?v=yRRQ6filg-E';
test('reading tab metadata does not launch a native process; a completed quality probe closes it',async()=>{const b=background();const page=await b.send({action:'page'});assert.equal(page.ok,true);assert.equal(b.calls.length,0);const info=await b.send({action:'probe',url,tabId:1});assert.equal(info.ok,true);assert.deepEqual(b.calls,['connect','probe','disconnect']);});
test('web pages and content scripts cannot start native operations',async()=>{const b=background();for(const s of [{id:'test',url:'https://www.youtube.com/watch?v=yRRQ6filg-E',tab:{id:1}},{id:'other',url:'chrome-extension://test/popup.html'}])assert.equal((await b.send({action:'probe',url,tabId:1},s)).ok,false);assert.equal(b.calls.length,0);});
test('SPA navigation uses the clicked current video while keeping the sender and active tab checks',async()=>{const b=background(),sender={id:'test',url:'https://www.youtube.com/',frameId:0,tab:{id:1,windowId:3}};assert.equal((await b.send({action:'open',url},sender)).ok,true);assert.deepEqual(b.calls,['popup']);for(const s of [{...sender,frameId:1},{...sender,id:'other'},{...sender,url:'https://youtube.com.evil.com/'},{...sender,tab:{id:2,windowId:3}}])assert.equal((await b.send({action:'open',url},s)).ok,false);assert.equal((await b.send({action:'open',url:'https://www.youtube.com/watch?v=mqK1eU5k2CQ'},sender)).ok,false);assert.equal((await b.send({action:'open',url:'file:///C:/video'},sender)).ok,false);assert.deepEqual(b.calls,['popup']);});
test('downloads require current tab, freshly read metadata and exact offered quality',async()=>{const b=background();assert.equal((await b.send({action:'start',url,tabId:1,quality:'1080'})).ok,false);await b.send({action:'probe',url,tabId:1});assert.equal((await b.send({action:'start',url,tabId:1,quality:'720'})).ok,false);b.tab({id:2,url,title:'News'});assert.equal((await b.send({action:'start',url,tabId:1,quality:'1080'})).ok,false);});
test('native process exits after the terminal job; completed state stays immutable',async()=>{const b=background();await b.send({action:'probe',url,tabId:1});const r=await b.send({action:'start',url,tabId:1,quality:'1080'});assert.equal(r.ok,true);assert.equal(b.calls.filter(c=>c==='disconnect').length,1);b.events.nativeMessage({event:'job',job:{id:r.data.id,status:'completed',progress:100,path:'C:/video.mp4'}});await new Promise(resolve=>setTimeout(resolve,10));assert.equal(b.calls.filter(c=>c==='disconnect').length,2);assert.equal(b.state.history[0].status,'completed');b.events.nativeMessage({event:'job',job:{id:r.data.id,status:'failed',error:'late'}});await new Promise(resolve=>setTimeout(resolve,10));assert.equal(b.state.history[0].status,'completed');});
test('package has only native and YouTube access, with no browser media engine or cookies',()=>{const m=JSON.parse(fs.readFileSync(new URL('../extension/manifest.json',import.meta.url)));assert.deepEqual(m.permissions,['activeTab','storage','nativeMessaging']);assert.deepEqual(m.host_permissions,['https://www.youtube.com/*']);for(const file of ['engine.bundle.js','sabr.bundle.js','offscreen.js','scan.js'])assert.equal(fs.existsSync(new URL('../extension/'+file,import.meta.url)),false);});
