import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';
const root=path.resolve('extension'),out=path.resolve('test-output/rebuild-ui');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(root,req.url.slice(1)||'popup.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({channel:'msedge',headless:true});const errors=[];
try{
 for(const scheme of ['light','dark']){
  const context=await browser.newContext({viewport:{width:368,height:600},colorScheme:scheme});await context.addInitScript(()=>{window.calls=[];window.chrome={runtime:{openOptionsPage(){},sendMessage:async m=>{calls.push(m);return {ok:true,data:m.action==='page'?{title:'68歲許純美消失9年現況曝！',url:'https://www.youtube.com/watch?v=yRRQ6filg-E',tabId:1}:m.action==='probe'?{id:'yRRQ6filg-E',title:'68歲許純美消失9年現況曝！',uploader:'三立新聞網',duration:103,qualities:[{height:2160,width:3840},{height:1080,width:1920}]}:{cancelled:true}};}},storage:{local:{get:async()=>({history:[]})},onChanged:{addListener(){}}}};});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/popup.html`);await page.locator('#probe:not([disabled])').waitFor();await page.locator('#settings:not([hidden])').waitFor();assert.equal(await page.locator('#quality').inputValue(),'1080');await page.locator('#download').click();await page.getByText('已取消。',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'popup-'+scheme+'.png'),fullPage:true});await context.close();
 }
 const context=await browser.newContext({viewport:{width:1000,height:640},colorScheme:'light'});await context.route('https://www.youtube.com/**',route=>route.fulfill({contentType:'text/html; charset=utf-8',body:'<html><body><ytd-watch-flexy><div id="top-level-buttons-computed"><span><button aria-label="分享">分享</button></span></div></ytd-watch-flexy></body></html>'}));const page=await context.newPage();await page.goto('https://www.youtube.com/watch?v=yRRQ6filg-E');await page.addInitScript(()=>{window.chrome={runtime:{sendMessage:async()=>({ok:true})}};});await page.evaluate(()=>{window.chrome={runtime:{sendMessage:async()=>({ok:true})}};});await page.addScriptTag({path:path.join(root,'youtube-button.js')});const button=page.locator('#tubenest-download button');await button.waitFor();
 const color=()=>button.evaluate(b=>({fg:getComputedStyle(b).color,bg:getComputedStyle(b).backgroundColor,stroke:getComputedStyle(b.querySelector('svg')).stroke}));const light=await color();assert.equal(light.fg,'rgb(15, 15, 15)');assert.equal(light.stroke,light.fg);await page.screenshot({path:path.join(out,'button-light.png')});await page.evaluate(()=>{document.documentElement.setAttribute('dark','');document.body.style.background='#0f0f0f';});await page.waitForFunction(()=>document.getElementById('tubenest-download').hasAttribute('dark'));const dark=await color();assert.equal(dark.fg,'rgb(241, 241, 241)');assert.equal(dark.stroke,dark.fg);assert.notEqual(dark.bg,light.bg);await page.screenshot({path:path.join(out,'button-dark.png')});assert.equal(await page.evaluate(()=>document.getElementById('tubenest-download').previousElementSibling.textContent),'分享');await button.click();await page.evaluate(()=>{history.pushState({},'', '/');document.dispatchEvent(new Event('yt-navigate-finish'));});assert.equal(await page.locator('#tubenest-download').count(),0);await context.close();assert.deepEqual(errors,[]);
 console.log('PASS: popup flow, button-triggered probing, exact quality/cancel, light/dark button text and SVG, Share adjacency, SPA removal.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
